# .github/workflows/sql-workflow.yml
on: [push]
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: azure/sql-action@v2.2.1
      with:        
        connection-string: ${{ secrets.SQL_CONNECTION_STRING }}
        path: './Contoso/Contoso/Contoso.sqlproj'
        action: 'publish'
