name: Deploy SQL Server Project

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Visual Studio Build Tools
      run: |
        choco install visualstudio2019buildtools -y
        choco install visualstudio2019-workload-data -y
        choco install visualstudio2019-workload-manageddesktop -y
        choco install visualstudio2019-workload-netcoretools -y

    - name: Restore NuGet packages
      run: msbuild /t:restore ./Contoso/Contoso.sln

    - name: Build SQL Server project
      run: msbuild .Contoso/Contoso/Contoso.sln /p:Configuration=Release

    - name: Generate DACPAC
      run: |
        msbuild .Contoso/Contoso/Contoso/Contoso.sqlproj /p:Configuration=Release /p:OutputPath=./output
        echo "DACPAC generated in ./output"

    - name: Install sqlcmd
      run: |
        Invoke-WebRequest -Uri https://aka.ms/sqlcmd-msi -OutFile sqlcmd.msi
        Start-Process msiexec.exe -ArgumentList '/i sqlcmd.msi /quiet /norestart' -Wait

    - name: Deploy to SQL Server
      env:
        SQL_SERVER: ${{ secrets.SQL_SERVER }}
        SQL_DATABASE: ${{ secrets.SQL_DATABASE }}
        SQL_USERNAME: ${{ secrets.SQL_USERNAME }}
        SQL_PASSWORD: ${{ secrets.SQL_PASSWORD }}
      run: |
        sqlcmd -S $env:SQL_SERVER -d $env:SQL_DATABASE -U $env:SQL_USERNAME -P $env:SQL_PASSWORD -i ./output/deploy.sql
