name: Deploy SQL Server Project

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0' 

    - name: Restore NuGet packages
      run: dotnet restore ./Contoso/Contoso.sln

    - name: Build SQL Server project
      run: dotnet build ./Contoso/Contoso.sln --configuration Debug

    - name: Generate DACPAC
      run: |
        dotnet build ./Contoso/Contoso/Contoso.sqlproj /p:Configuration=Debug /p:OutputPath=./output
        echo "DACPAC generated in ./output"
    
    - name: Install sqlcmd
      run: |
        Invoke-WebRequest -Uri https://aka.ms/sqlcmd-msi -OutFile sqlcmd.msi
        Start-Process msiexec.exe -ArgumentList '/i sqlcmd.msi /quiet /norestart' -Wait
        
    - name: Deploy to SQL Server
      env:
        SQL_SERVER: XI039
        SQL_DATABASE: DmContosoTest
        SQL_USERNAME: test
        SQL_PASSWORD: test1
      run: |
        sqlcmd -S $env:SQL_SERVER -d $env:SQL_DATABASE -U $env:SQL_USERNAME -P $env:SQL_PASSWORD -i ./output/Contoso_Create.sql

