name: Deploy SQL Server Project

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up MSBuild
      uses: microsoft/setup-msbuild@v1.0.3

    - name: Restore NuGet packages
      run: msbuild /t:restore ./Contoso/Contoso.sln

    - name: Build SQL Server project
      run: msbuild ./Contoso/Contoso.sln /p:Configuration=Release
    
    - name: Install PowerShell 7
      run: |
        Invoke-WebRequest -Uri https://github.com/PowerShell/PowerShell/releases/download/v7.2.0/PowerShell-7.2.0-win-x64.msi -OutFile PowerShell-7.2.0-win-x64.msi
        Start-Process msiexec.exe -ArgumentList '/i', 'PowerShell-7.2.0-win-x64.msi', '/quiet', '/norestart' -NoNewWindow -Wait

    - name: Install SqlPackage
      shell: pwsh
      run: |
        Invoke-WebRequest -Uri https://aka.ms/sqlpackage -OutFile sqlpackage.zip
        Expand-Archive sqlpackage.zip -DestinationPath ./sqlpackage
    
    - name: Generate DACPAC
      run: |
        msbuild ./Contoso/Contoso/Contoso.sqlproj /p:Configuration=Release /p:OutputPath=./output
        echo "DACPAC generated in ./output"
   
    - name: Install sqlcmd
      run: |
        Invoke-WebRequest -Uri https://aka.ms/sqlcmd-msi -OutFile sqlcmd.msi
        Start-Process msiexec.exe -ArgumentList '/i sqlcmd.msi /quiet /norestart' -Wait

    - name: Deploy to SQL Server
      env:
        SQL_SERVER: XI039
        SQL_DATABASE: DmContosoTest
        SQL_USERNAME: testing
        SQL_PASSWORD: testing1
      run: |
        ./sqlpackage/sqlpackage.exe /Action:Publish /SourceFile:"./output/Contoso.dacpac" /TargetServerName:"$env:SQL_SERVER" /TargetDatabaseName:"$env:SQL_DATABASE" /TargetUser:"$env:SQL_USERNAME" /TargetPassword:"$env:SQL_PASSWORD" /p:DropObjectsNotInSource=True
